// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class Announcement
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Title { get; set; }

    [Required]
    public string AnnouncementBody { get; set; }

    public int SupervisorId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime PostTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastEditTime { get; set; }

    public int? LastEditBy { get; set; }

    public bool IsDeleted { get; set; }

    public int StatusId { get; set; }

    [Column("ImageURL")]
    [StringLength(250)]
    public string ImageUrl { get; set; }

    [ForeignKey("LastEditBy")]
    [InverseProperty("AnnouncementLastEditByNavigations")]
    public virtual User LastEditByNavigation { get; set; }

    [ForeignKey("StatusId")]
    [InverseProperty("Announcements")]
    public virtual PostStatus Status { get; set; }

    [ForeignKey("SupervisorId")]
    [InverseProperty("AnnouncementSupervisors")]
    public virtual User Supervisor { get; set; }
}