// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class Branch
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(255)]
    public string Address { get; set; }

    [StringLength(20)]
    public string Phone { get; set; }

    [Column("MapURL")]
    [StringLength(500)]
    public string MapUrl { get; set; }

    public int RegionId { get; set; }

    public bool IsVisible { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("Branch")]
    public virtual ICollection<BranchOpenTime> BranchOpenTimes { get; set; } = new List<BranchOpenTime>();

    [InverseProperty("Location")]
    public virtual ICollection<Event> Events { get; set; } = new List<Event>();

    [ForeignKey("RegionId")]
    [InverseProperty("Branches")]
    public virtual Region Region { get; set; }
}