// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Table("BranchOpenTime")]
public partial class BranchOpenTime
{
    [Key]
    public int Id { get; set; }

    public int BranchId { get; set; }

    public byte Weekday { get; set; }

    public TimeOnly? OpenTime { get; set; }

    public TimeOnly? CloseTime { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("BranchOpenTimes")]
    public virtual Branch Branch { get; set; }
}