// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("BrandName", Name = "UQ__Brands__2206CE9B14BB0E2B", IsUnique = true)]
public partial class Brand
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string BrandName { get; set; }

    [StringLength(255)]
    public string LogoUrl { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("BrandCreatedByNavigations")]
    public virtual User CreatedByNavigation { get; set; }

    [ForeignKey("DeletedBy")]
    [InverseProperty("BrandDeletedByNavigations")]
    public virtual User DeletedByNavigation { get; set; }

    [InverseProperty("Brand")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    [ForeignKey("UpdatedBy")]
    [InverseProperty("BrandUpdatedByNavigations")]
    public virtual User UpdatedByNavigation { get; set; }
}