// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Table("BrowseHistory")]
public partial class BrowseHistory
{
    [Key]
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int ProductId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ViewedAt { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("BrowseHistories")]
    public virtual Member Member { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("BrowseHistories")]
    public virtual Product Product { get; set; }
}