// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("CategoryName", Name = "UQ__Categori__8517B2E09D233A93", IsUnique = true)]
public partial class Category
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string CategoryName { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    public int? ParentCategoryId { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("CategoryCreatedByNavigations")]
    public virtual User CreatedByNavigation { get; set; }

    [ForeignKey("DeletedBy")]
    [InverseProperty("CategoryDeletedByNavigations")]
    public virtual User DeletedByNavigation { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    [ForeignKey("UpdatedBy")]
    [InverseProperty("CategoryUpdatedByNavigations")]
    public virtual User UpdatedByNavigation { get; set; }
}