// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class ChatConversation
{
    [Key]
    public int Id { get; set; }

    public int MemberId { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Status { get; set; }

    public int? AssignedAgentId { get; set; }

    [Precision(0)]
    public DateTime? TakenAt { get; set; }

    [Precision(0)]
    public DateTime LastMessageAt { get; set; }

    [Precision(0)]
    public DateTime CreatedAt { get; set; }

    [InverseProperty("Conversation")]
    public virtual ICollection<ChatMessage> ChatMessages { get; set; } = new List<ChatMessage>();

    [ForeignKey("MemberId")]
    [InverseProperty("ChatConversation")]
    public virtual Member Member { get; set; }
}