// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("ConversationId", "CreatedAt", Name = "IX_ChatMessages_Conv_CreatedAt")]
public partial class ChatMessage
{
    [Key]
    public int Id { get; set; }

    public int ConversationId { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Sender { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Type { get; set; }

    [StringLength(2000)]
    public string Content { get; set; }

    public int? ProductId { get; set; }

    [StringLength(500)]
    public string Url { get; set; }

    [Precision(0)]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("ConversationId")]
    [InverseProperty("ChatMessages")]
    public virtual ChatConversation Conversation { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ChatMessages")]
    public virtual Product Product { get; set; }
}