// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class Comment
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(500)]
    public string CommentText { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CommentTime { get; set; }

    public int PostId { get; set; }

    public int MemberId { get; set; }

    public bool IsDeleted { get; set; }

    public int? ReplyToCommentId { get; set; }

    public int NumOfGoods { get; set; }

    [InverseProperty("Comment")]
    public virtual ICollection<CommentGood> CommentGoods { get; set; } = new List<CommentGood>();

    [InverseProperty("Comment")]
    public virtual ICollection<CommentReport> CommentReports { get; set; } = new List<CommentReport>();

    [InverseProperty("ReplyToComment")]
    public virtual ICollection<Comment> InverseReplyToComment { get; set; } = new List<Comment>();

    [ForeignKey("MemberId")]
    [InverseProperty("Comments")]
    public virtual Member Member { get; set; }

    [ForeignKey("PostId")]
    [InverseProperty("Comments")]
    public virtual Post Post { get; set; }

    [ForeignKey("ReplyToCommentId")]
    [InverseProperty("InverseReplyToComment")]
    public virtual Comment ReplyToComment { get; set; }
}