// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[PrimaryKey("MemberId", "CommentId")]
public partial class CommentGood
{
    [Key]
    public int MemberId { get; set; }

    [Key]
    public int CommentId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedTime { get; set; }

    [ForeignKey("CommentId")]
    [InverseProperty("CommentGoods")]
    public virtual Comment Comment { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("CommentGoods")]
    public virtual Member Member { get; set; }
}