// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class CompanyEvent
{
    [Key]
    public int Id { get; set; }

    public int Year { get; set; }

    public int? Month { get; set; }

    [Required]
    [StringLength(200)]
    public string Title { get; set; }

    public string Description { get; set; }

    [StringLength(500)]
    public string ImageUrl { get; set; }

    [StringLength(500)]
    public string VideoUrl { get; set; }

    public int? OrderInYear { get; set; }

    public bool? IsMajor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    public int? CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("CompanyEventCreatedByNavigations")]
    public virtual User CreatedByNavigation { get; set; }

    [ForeignKey("DeletedBy")]
    [InverseProperty("CompanyEventDeletedByNavigations")]
    public virtual User DeletedByNavigation { get; set; }

    [ForeignKey("UpdatedBy")]
    [InverseProperty("CompanyEventUpdatedByNavigations")]
    public virtual User UpdatedByNavigation { get; set; }
}