// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("CustomOrderId", Name = "UQ__CustomOr__BA69D88FCC550116", IsUnique = true)]
public partial class CustomOrderDesign
{
    [Key]
    public int Id { get; set; }

    public int CustomOrderId { get; set; }

    [StringLength(255)]
    public string ShirtColorUrl { get; set; }

    [StringLength(10)]
    public string GhostColorHex { get; set; }

    [StringLength(255)]
    public string EyeImageUrl { get; set; }

    [StringLength(255)]
    public string AccessoryImageUrl { get; set; }

    [StringLength(100)]
    public string CustomText { get; set; }

    public string CanvasImageBase64 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("CustomOrderId")]
    [InverseProperty("CustomOrderDesign")]
    public virtual CustomOrder CustomOrder { get; set; }

    [ForeignKey("UpdatedBy")]
    [InverseProperty("CustomOrderDesigns")]
    public virtual User UpdatedByNavigation { get; set; }
}