// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("OrderId", Name = "UQ__CustomOr__C3905BCE674998E0", IsUnique = true)]
public partial class CustomOrder
{
    [Key]
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int MemberId { get; set; }

    public string RequestDetail { get; set; }

    public bool IsApproved { get; set; }

    [StringLength(50)]
    public string ApprovedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ApprovedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    [InverseProperty("CustomOrder")]
    public virtual CustomOrderDesign CustomOrderDesign { get; set; }

    [ForeignKey("DeletedBy")]
    [InverseProperty("CustomOrderDeletedByNavigations")]
    public virtual User DeletedByNavigation { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("CustomOrders")]
    public virtual Member Member { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("CustomOrder")]
    public virtual Order Order { get; set; }

    [ForeignKey("UpdatedBy")]
    [InverseProperty("CustomOrderUpdatedByNavigations")]
    public virtual User UpdatedByNavigation { get; set; }
}