// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("ShippingName", Name = "UQ__Delivery__194FD18F453EEC39", IsUnique = true)]
public partial class DeliveryMethod
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string ShippingName { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    [Column(TypeName = "decimal(10, 0)")]
    public decimal BaseShippingCost { get; set; }

    public bool IsActive { get; set; }

    public int? DefaultDeliveryTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("DeliveryMethodCreatedByNavigations")]
    public virtual User CreatedByNavigation { get; set; }

    [ForeignKey("DeletedBy")]
    [InverseProperty("DeliveryMethodDeletedByNavigations")]
    public virtual User DeletedByNavigation { get; set; }

    [InverseProperty("Delivery")]
    public virtual DeliveryRule DeliveryRule { get; set; }

    [InverseProperty("DeliveryMethod")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    [InverseProperty("Delivery")]
    public virtual ICollection<ProductDelivery> ProductDeliveries { get; set; } = new List<ProductDelivery>();

    [ForeignKey("UpdatedBy")]
    [InverseProperty("DeliveryMethodUpdatedByNavigations")]
    public virtual User UpdatedByNavigation { get; set; }
}