// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("DeliveryId", Name = "UQ__Delivery__626D8FCFF5E2F30E", IsUnique = true)]
public partial class DeliveryRule
{
    [Key]
    public int Id { get; set; }

    public int DeliveryId { get; set; }

    [Column(TypeName = "decimal(10, 0)")]
    public decimal? MaxWeight { get; set; }

    [Column(TypeName = "decimal(10, 0)")]
    public decimal? MaxLength { get; set; }

    [Column(TypeName = "decimal(10, 0)")]
    public decimal? MaxWidth { get; set; }

    [Column(TypeName = "decimal(10, 0)")]
    public decimal? MaxHeight { get; set; }

    [Column(TypeName = "decimal(10, 0)")]
    public decimal? MaxTotalDimension { get; set; }

    [ForeignKey("DeliveryId")]
    [InverseProperty("DeliveryRule")]
    public virtual DeliveryMethod Delivery { get; set; }
}