// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("EcpayTradeNo", Name = "UQ__EcpayPay__3C4E1BE4259E8585", IsUnique = true)]
[Index("OrderId", Name = "UQ__EcpayPay__C3905BCEB5151A7B", IsUnique = true)]
public partial class EcpayPayment
{
    [Key]
    public int Id { get; set; }

    public int OrderId { get; set; }

    [Required]
    [StringLength(100)]
    public string EcpayTradeNo { get; set; }

    [StringLength(100)]
    public string MerchantTradeNo { get; set; }

    [Column(TypeName = "decimal(10, 0)")]
    public decimal PayAmount { get; set; }

    [Required]
    [StringLength(50)]
    public string PayStatus { get; set; }

    [StringLength(50)]
    public string PaymentType { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime PayTime { get; set; }

    public string ExtraInfo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    [ForeignKey("DeletedBy")]
    [InverseProperty("EcpayPaymentDeletedByNavigations")]
    public virtual User DeletedByNavigation { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("EcpayPayment")]
    public virtual Order Order { get; set; }

    [ForeignKey("UpdatedBy")]
    [InverseProperty("EcpayPaymentUpdatedByNavigations")]
    public virtual User UpdatedByNavigation { get; set; }
}