// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Table("EventRegistration")]
public partial class EventRegistration
{
    [Key]
    public int Id { get; set; }

    public int EventId { get; set; }

    public int MemberId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime SignupTime { get; set; }

    public int SignupPeople { get; set; }

    [StringLength(20)]
    public string PaymentStatus { get; set; }

    [StringLength(20)]
    public string PaymentMethod { get; set; }

    [Column("TransactionID")]
    [StringLength(50)]
    public string TransactionId { get; set; }

    [StringLength(20)]
    public string EnrollmentStatus { get; set; }

    [ForeignKey("EventId")]
    [InverseProperty("EventRegistrations")]
    public virtual Event Event { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("EventRegistrations")]
    public virtual Member Member { get; set; }
}