// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class EventDetail
{
    [Key]
    public int Id { get; set; }

    public int EventId { get; set; }

    public int? StepOrder { get; set; }

    public string Content { get; set; }

    [ForeignKey("EventId")]
    [InverseProperty("EventDetails")]
    public virtual Event Event { get; set; }
}