// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class EventFeedback
{
    [Key]
    public int Id { get; set; }

    public int EventId { get; set; }

    public int MemberId { get; set; }

    public int? Rating { get; set; }

    public string Comment { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("EventId")]
    [InverseProperty("EventFeedbacks")]
    public virtual Event Event { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("EventFeedbacks")]
    public virtual Member Member { get; set; }
}