// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Table("EventType")]
public partial class EventType
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(20)]
    public string Name { get; set; }

    [StringLength(100)]
    public string Icon { get; set; }

    public bool IsVisible { get; set; }

    [InverseProperty("Type")]
    public virtual ICollection<Event> Events { get; set; } = new List<Event>();
}