// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class Event
{
    [Key]
    public int Id { get; set; }

    public int TypeId { get; set; }

    [Required]
    [StringLength(50)]
    public string Title { get; set; }

    public string Description { get; set; }

    [StringLength(200)]
    public string EventPhotos { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndTime { get; set; }

    public int LocationId { get; set; }

    public int InstructorId { get; set; }

    public int? Capacity { get; set; }

    [Column(TypeName = "decimal(10, 0)")]
    public decimal? Price { get; set; }

    public int StatusId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("Event")]
    public virtual ICollection<EventDetail> EventDetails { get; set; } = new List<EventDetail>();

    [InverseProperty("Event")]
    public virtual ICollection<EventFeedback> EventFeedbacks { get; set; } = new List<EventFeedback>();

    [InverseProperty("Event")]
    public virtual ICollection<EventRegistration> EventRegistrations { get; set; } = new List<EventRegistration>();

    [ForeignKey("InstructorId")]
    [InverseProperty("Events")]
    public virtual Instructor Instructor { get; set; }

    [ForeignKey("LocationId")]
    [InverseProperty("Events")]
    public virtual Branch Location { get; set; }

    [ForeignKey("StatusId")]
    [InverseProperty("Events")]
    public virtual PostStatus Status { get; set; }

    [ForeignKey("TypeId")]
    [InverseProperty("Events")]
    public virtual EventType Type { get; set; }
}