// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class Faq
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(200)]
    public string Question { get; set; }

    [Required]
    public string Answer { get; set; }

    [StringLength(200)]
    public string Keywords { get; set; }

    public bool IsActive { get; set; }
}