// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("Name", Name = "UQ__GiftRule__737584F6653F89F0", IsUnique = true)]
public partial class GiftRule
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [StringLength(50)]
    public string ConditionType { get; set; }

    [Column(TypeName = "decimal(10, 0)")]
    public decimal ConditionValue { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("GiftRuleCreatedByNavigations")]
    public virtual User CreatedByNavigation { get; set; }

    [ForeignKey("DeletedBy")]
    [InverseProperty("GiftRuleDeletedByNavigations")]
    public virtual User DeletedByNavigation { get; set; }

    [InverseProperty("Rule")]
    public virtual ICollection<GiftRuleItem> GiftRuleItems { get; set; } = new List<GiftRuleItem>();

    [InverseProperty("GiftRule")]
    public virtual ICollection<OrderGift> OrderGifts { get; set; } = new List<OrderGift>();

    [ForeignKey("UpdatedBy")]
    [InverseProperty("GiftRuleUpdatedByNavigations")]
    public virtual User UpdatedByNavigation { get; set; }
}