// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("Name", Name = "UQ__Gifts__737584F61FE3E334", IsUnique = true)]
public partial class Gift
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    [StringLength(255)]
    public string ImageUrl { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("GiftCreatedByNavigations")]
    public virtual User CreatedByNavigation { get; set; }

    [ForeignKey("DeletedBy")]
    [InverseProperty("GiftDeletedByNavigations")]
    public virtual User DeletedByNavigation { get; set; }

    [InverseProperty("Gift")]
    public virtual ICollection<GiftRuleItem> GiftRuleItems { get; set; } = new List<GiftRuleItem>();

    [InverseProperty("Gift")]
    public virtual ICollection<OrderGift> OrderGifts { get; set; } = new List<OrderGift>();

    [ForeignKey("UpdatedBy")]
    [InverseProperty("GiftUpdatedByNavigations")]
    public virtual User UpdatedByNavigation { get; set; }
}