// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class GiftRuleItem
{
    [Key]
    public int Id { get; set; }

    public int RuleId { get; set; }

    public int GiftId { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("GiftRuleItemCreatedByNavigations")]
    public virtual User CreatedByNavigation { get; set; }

    [ForeignKey("DeletedBy")]
    [InverseProperty("GiftRuleItemDeletedByNavigations")]
    public virtual User DeletedByNavigation { get; set; }

    [ForeignKey("GiftId")]
    [InverseProperty("GiftRuleItems")]
    public virtual Gift Gift { get; set; }

    [ForeignKey("RuleId")]
    [InverseProperty("GiftRuleItems")]
    public virtual GiftRule Rule { get; set; }

    [ForeignKey("UpdatedBy")]
    [InverseProperty("GiftRuleItemUpdatedByNavigations")]
    public virtual User UpdatedByNavigation { get; set; }
}