// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("LinepayTransactionId", Name = "UQ__LinepayP__8430CEB6784095D6", IsUnique = true)]
[Index("OrderId", Name = "UQ__LinepayP__C3905BCE7683579C", IsUnique = true)]
public partial class LinepayPayment
{
    [Key]
    public int Id { get; set; }

    public int OrderId { get; set; }

    [Required]
    [StringLength(100)]
    public string LinepayTransactionId { get; set; }

    [Column(TypeName = "decimal(10, 0)")]
    public decimal PayAmount { get; set; }

    [Required]
    [StringLength(50)]
    public string PayStatus { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime PayTime { get; set; }

    public string ExtraInfo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    [ForeignKey("DeletedBy")]
    [InverseProperty("LinepayPaymentDeletedByNavigations")]
    public virtual User DeletedByNavigation { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("LinepayPayment")]
    public virtual Order Order { get; set; }

    [ForeignKey("UpdatedBy")]
    [InverseProperty("LinepayPaymentUpdatedByNavigations")]
    public virtual User UpdatedByNavigation { get; set; }
}