// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("City", "District", Name = "IX_City_District")]
[Index("Provider", "LogisticsSubType", "StoreId", Name = "UX_Store_Uniq", IsUnique = true)]
public partial class LogisticsStoreGeocode
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(20)]
    public string Provider { get; set; }

    [Required]
    [StringLength(20)]
    public string LogisticsSubType { get; set; }

    [Required]
    [StringLength(32)]
    public string StoreId { get; set; }

    [Required]
    [StringLength(100)]
    public string StoreName { get; set; }

    [Required]
    [StringLength(255)]
    public string Address { get; set; }

    [StringLength(255)]
    public string AddressNormalized { get; set; }

    [StringLength(64)]
    [Unicode(false)]
    public string AddressHash { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal Latitude { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal Longitude { get; set; }

    [Required]
    [StringLength(20)]
    public string Geocoder { get; set; }

    public string RawJson { get; set; }

    [Required]
    [StringLength(20)]
    public string Status { get; set; }

    [StringLength(500)]
    public string ErrorMessage { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastGeocodedAt { get; set; }

    [StringLength(50)]
    public string City { get; set; }

    [StringLength(50)]
    public string District { get; set; }

    [StringLength(10)]
    public string PostalCode { get; set; }
}