// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class MassNotification
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(255)]
    public string Title { get; set; }

    [Required]
    public string Content { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime PublishTime { get; set; }

    public bool IsActive { get; set; }

    public int TargetAudienceType { get; set; }

    public int CreatorId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ExpireTime { get; set; }

    [StringLength(512)]
    public string Link { get; set; }

    [ForeignKey("CreatorId")]
    [InverseProperty("MassNotifications")]
    public virtual User Creator { get; set; }
}