// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Table("MemberAddress")]
public partial class MemberAddress
{
    [Key]
    public int Id { get; set; }

    public int? MemberId { get; set; }

    [StringLength(100)]
    public string RecipientName { get; set; }

    [StringLength(20)]
    public string RecipientPhone { get; set; }

    [StringLength(10)]
    public string PostalCode { get; set; }

    [StringLength(50)]
    public string City { get; set; }

    [StringLength(50)]
    public string District { get; set; }

    [StringLength(255)]
    public string Street { get; set; }

    public bool? IsDefault { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [StringLength(50)]
    public string Label { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("MemberAddresses")]
    public virtual Member Member { get; set; }
}