// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class MemberPointLog
{
    [Key]
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int? OrderId { get; set; }

    public int ChangeAmount { get; set; }

    [StringLength(100)]
    public string Reason { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("MemberPointLogs")]
    public virtual Member Member { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("MemberPointLogs")]
    public virtual Order Order { get; set; }
}