// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class MemberProfile
{
    [Key]
    public int Id { get; set; }

    public int MemberId { get; set; }

    [StringLength(50)]
    public string RealName { get; set; }

    [StringLength(10)]
    public string Gender { get; set; }

    public DateOnly? Birthdate { get; set; }

    [StringLength(20)]
    public string Phone { get; set; }

    [StringLength(255)]
    public string Photo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("MemberProfiles")]
    public virtual Member Member { get; set; }
}