// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("UserName", Name = "UQ_Members_UserName", IsUnique = true)]
[Index("Email", Name = "UQ__Members__A9D10534C842FAC4", IsUnique = true)]
public partial class Member
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string UserName { get; set; }

    [Required]
    [StringLength(150)]
    public string Email { get; set; }

    [StringLength(200)]
    public string Password { get; set; }

    public bool IsActive { get; set; }

    public bool IsConfirmed { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Required]
    [StringLength(10)]
    public string LoginProvider { get; set; }

    [InverseProperty("Member")]
    public virtual ICollection<BrowseHistory> BrowseHistories { get; set; } = new List<BrowseHistory>();

    [InverseProperty("Member")]
    public virtual ChatConversation ChatConversation { get; set; }

    [InverseProperty("Member")]
    public virtual ICollection<CommentGood> CommentGoods { get; set; } = new List<CommentGood>();

    [InverseProperty("Reporter")]
    public virtual ICollection<CommentReport> CommentReports { get; set; } = new List<CommentReport>();

    [InverseProperty("Member")]
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    [InverseProperty("Member")]
    public virtual ICollection<CustomOrder> CustomOrders { get; set; } = new List<CustomOrder>();

    [InverseProperty("Member")]
    public virtual ICollection<EventFeedback> EventFeedbacks { get; set; } = new List<EventFeedback>();

    [InverseProperty("Member")]
    public virtual ICollection<EventRegistration> EventRegistrations { get; set; } = new List<EventRegistration>();

    [InverseProperty("Member")]
    public virtual ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();

    [InverseProperty("Member")]
    public virtual ICollection<MemberAddress> MemberAddresses { get; set; } = new List<MemberAddress>();

    [InverseProperty("Member")]
    public virtual ICollection<MemberCvsAddress> MemberCvsAddresses { get; set; } = new List<MemberCvsAddress>();

    [InverseProperty("Member")]
    public virtual ICollection<MemberLoginLog> MemberLoginLogs { get; set; } = new List<MemberLoginLog>();

    [InverseProperty("Member")]
    public virtual ICollection<MemberPointLog> MemberPointLogs { get; set; } = new List<MemberPointLog>();

    [InverseProperty("Member")]
    public virtual ICollection<MemberProfile> MemberProfiles { get; set; } = new List<MemberProfile>();

    [InverseProperty("Member")]
    public virtual ICollection<MemberVerification> MemberVerifications { get; set; } = new List<MemberVerification>();

    [InverseProperty("Member")]
    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    [InverseProperty("Member")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    [InverseProperty("Member")]
    public virtual ICollection<PointLot> PointLots { get; set; } = new List<PointLot>();

    [InverseProperty("Member")]
    public virtual ICollection<PointRedemption> PointRedemptions { get; set; } = new List<PointRedemption>();

    [InverseProperty("Member")]
    public virtual ICollection<PostFavorite> PostFavorites { get; set; } = new List<PostFavorite>();

    [InverseProperty("Member")]
    public virtual ICollection<PostGood> PostGoods { get; set; } = new List<PostGood>();

    [InverseProperty("Reporter")]
    public virtual ICollection<PostReport> PostReports { get; set; } = new List<PostReport>();

    [InverseProperty("Member")]
    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    [InverseProperty("Member")]
    public virtual ICollection<ProductReview> ProductReviews { get; set; } = new List<ProductReview>();

    [InverseProperty("Member")]
    public virtual ICollection<Punishment> Punishments { get; set; } = new List<Punishment>();

    [InverseProperty("Member")]
    public virtual ICollection<SearchLog> SearchLogs { get; set; } = new List<SearchLog>();

    [InverseProperty("Member")]
    public virtual ShoppingCart ShoppingCart { get; set; }
}