// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("MemberId", "LogisticsSubType", Name = "IX_MemberCvsAddresses_Member_SubType")]
[Index("MemberId", "LogisticsSubType", "StoreId", Name = "UX_MemberCvsAddresses_Member_SubType_Store", IsUnique = true)]
public partial class MemberCvsAddress
{
    [Key]
    public int Id { get; set; }

    public int MemberId { get; set; }

    [Required]
    [StringLength(50)]
    public string LogisticsSubType { get; set; }

    [Required]
    [StringLength(50)]
    public string StoreId { get; set; }

    [Required]
    [StringLength(100)]
    public string StoreName { get; set; }

    [Required]
    [StringLength(200)]
    public string Address { get; set; }

    [StringLength(50)]
    public string Telephone { get; set; }

    public bool IsDefault { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [StringLength(100)]
    public string RecipientName { get; set; }

    [StringLength(20)]
    public string RecipientPhone { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("MemberCvsAddresses")]
    public virtual Member Member { get; set; }
}