// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class News
{
    [Key]
    public int Id { get; set; }

    public int CategoryId { get; set; }

    [Required]
    [StringLength(150)]
    public string Title { get; set; }

    [Required]
    public string Content { get; set; }

    [Column("ImageURL")]
    [StringLength(250)]
    public string ImageUrl { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PublishedAt { get; set; }

    public bool IsPinned { get; set; }

    public int StatusId { get; set; }

    public int ViewCountToday { get; set; }

    public int ViewCountTotal { get; set; }

    public int UserId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("News")]
    public virtual NewsCategory Category { get; set; }

    [ForeignKey("StatusId")]
    [InverseProperty("News")]
    public virtual PostStatus Status { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("News")]
    public virtual User User { get; set; }
}