// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class NewsCategory
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string CategoryName { get; set; }

    [StringLength(250)]
    public string Icon { get; set; }

    public bool IsVisible { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<News> News { get; set; } = new List<News>();
}