// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class Notification
{
    [Key]
    public int Id { get; set; }

    public int MemberId { get; set; }

    [Required]
    [StringLength(512)]
    public string NotificationText { get; set; }

    public bool IsRead { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Time { get; set; }

    public int TypeId { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("Notifications")]
    public virtual Member Member { get; set; }

    [ForeignKey("TypeId")]
    [InverseProperty("Notifications")]
    public virtual NotificationType Type { get; set; }
}