// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("OrderId", Name = "UQ__OrderLog__C3905BCEF9B0FAD3", IsUnique = true)]
public partial class OrderLogistic
{
    [Key]
    public int Id { get; set; }

    public int OrderId { get; set; }

    [Required]
    [StringLength(20)]
    public string Provider { get; set; }

    [Required]
    [StringLength(20)]
    public string LogisticsType { get; set; }

    [Required]
    [StringLength(20)]
    public string LogisticsSubType { get; set; }

    [StringLength(20)]
    public string PickupStoreId { get; set; }

    [StringLength(100)]
    public string PickupStoreName { get; set; }

    [StringLength(200)]
    public string PickupAddress { get; set; }

    [StringLength(30)]
    public string PickupTelephone { get; set; }

    public string PickupExtra { get; set; }

    public bool IsCollection { get; set; }

    [Column(TypeName = "decimal(10, 0)")]
    public decimal? CollectionAmount { get; set; }

    [Column("AllPayLogisticsID")]
    [StringLength(50)]
    public string AllPayLogisticsId { get; set; }

    [StringLength(50)]
    public string ShipmentNo { get; set; }

    public int? RtnCode { get; set; }

    [StringLength(100)]
    public string RtnMsg { get; set; }

    [StringLength(30)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderLogistic")]
    public virtual Order Order { get; set; }
}