// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class OrderGift
{
    [Key]
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int GiftId { get; set; }

    public int Quantity { get; set; }

    public int? GiftRuleId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("OrderGiftCreatedByNavigations")]
    public virtual User CreatedByNavigation { get; set; }

    [ForeignKey("DeletedBy")]
    [InverseProperty("OrderGiftDeletedByNavigations")]
    public virtual User DeletedByNavigation { get; set; }

    [ForeignKey("GiftId")]
    [InverseProperty("OrderGifts")]
    public virtual Gift Gift { get; set; }

    [ForeignKey("GiftRuleId")]
    [InverseProperty("OrderGifts")]
    public virtual GiftRule GiftRule { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderGifts")]
    public virtual Order Order { get; set; }

    [ForeignKey("UpdatedBy")]
    [InverseProperty("OrderGiftUpdatedByNavigations")]
    public virtual User UpdatedByNavigation { get; set; }
}