// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("OrderNumber", Name = "UQ__Orders__CAC5E743242CF264", IsUnique = true)]
public partial class Order
{
    [Key]
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int PaymentMethodId { get; set; }

    public int DeliveryMethodId { get; set; }

    [Required]
    [StringLength(20)]
    public string OrderNumber { get; set; }

    [Column(TypeName = "decimal(10, 0)")]
    public decimal TotalAmount { get; set; }

    [Column(TypeName = "decimal(10, 0)")]
    public decimal ShippingFee { get; set; }

    [Column(TypeName = "decimal(10, 0)")]
    public decimal? DiscountAmount { get; set; }

    public int UsedPoints { get; set; }

    public int PointsEarned { get; set; }

    public int StatusId { get; set; }

    [Required]
    [StringLength(20)]
    public string OrderType { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime OrderDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PaymentDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ShipDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CompletionDate { get; set; }

    public bool IsMixedPreorder { get; set; }

    [Required]
    [StringLength(100)]
    public string RecipientName { get; set; }

    [Required]
    [StringLength(20)]
    public string RecipientPhone { get; set; }

    [StringLength(255)]
    public string ShippingAddress { get; set; }

    [StringLength(10)]
    public string ShippingZipCode { get; set; }

    [StringLength(50)]
    public string InvoiceNumber { get; set; }

    [StringLength(20)]
    public string InvoiceType { get; set; }

    [StringLength(500)]
    public string Notes { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    [InverseProperty("Order")]
    public virtual CustomOrder CustomOrder { get; set; }

    [ForeignKey("DeletedBy")]
    [InverseProperty("OrderDeletedByNavigations")]
    public virtual User DeletedByNavigation { get; set; }

    [ForeignKey("DeliveryMethodId")]
    [InverseProperty("Orders")]
    public virtual DeliveryMethod DeliveryMethod { get; set; }

    [InverseProperty("Order")]
    public virtual EcpayPayment EcpayPayment { get; set; }

    [InverseProperty("Order")]
    public virtual LinepayPayment LinepayPayment { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("Orders")]
    public virtual Member Member { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<MemberPointLog> MemberPointLogs { get; set; } = new List<MemberPointLog>();

    [InverseProperty("Order")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    [InverseProperty("Order")]
    public virtual ICollection<OrderGift> OrderGifts { get; set; } = new List<OrderGift>();

    [InverseProperty("Order")]
    public virtual OrderLogistic OrderLogistic { get; set; }

    [ForeignKey("PaymentMethodId")]
    [InverseProperty("Orders")]
    public virtual PaymentMethod PaymentMethod { get; set; }

    [ForeignKey("StatusId")]
    [InverseProperty("Orders")]
    public virtual OrderStatus Status { get; set; }

    [ForeignKey("UpdatedBy")]
    [InverseProperty("OrderUpdatedByNavigations")]
    public virtual User UpdatedByNavigation { get; set; }
}