// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("MethodName", Name = "UQ__PaymentM__218CFB17A332F943", IsUnique = true)]
public partial class PaymentMethod
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string MethodName { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("PaymentMethodCreatedByNavigations")]
    public virtual User CreatedByNavigation { get; set; }

    [ForeignKey("DeletedBy")]
    [InverseProperty("PaymentMethodDeletedByNavigations")]
    public virtual User DeletedByNavigation { get; set; }

    [InverseProperty("PaymentMethod")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    [InverseProperty("Payment")]
    public virtual ICollection<ProductPayment> ProductPayments { get; set; } = new List<ProductPayment>();

    [ForeignKey("UpdatedBy")]
    [InverseProperty("PaymentMethodUpdatedByNavigations")]
    public virtual User UpdatedByNavigation { get; set; }
}