// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("Status", Name = "IX_PointRules_Status")]
[Index("TriggerType", Name = "IX_PointRules_Trigger")]
public partial class PointRule
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(120)]
    public string Name { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Status { get; set; }

    [Required]
    [StringLength(40)]
    [Unicode(false)]
    public string TriggerType { get; set; }

    [StringLength(64)]
    public string CustomEventKey { get; set; }

    public string ConditionsJson { get; set; }

    [Required]
    [StringLength(12)]
    [Unicode(false)]
    public string PointType { get; set; }

    public int? FixedAmount { get; set; }

    public int? RandomMin { get; set; }

    public int? RandomMax { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? Percentage { get; set; }

    public int? PerUserMonthlyLimit { get; set; }

    public int? TotalBudget { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string ExpiryMode { get; set; }

    public int? ExpiryDays { get; set; }

    [Precision(0)]
    public DateTime? ExpiryDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ScheduleCron { get; set; }

    [Precision(0)]
    public DateTime? StartAt { get; set; }

    [Precision(0)]
    public DateTime? EndAt { get; set; }

    [StringLength(50)]
    public string Target { get; set; }

    public bool NotifyEmail { get; set; }

    public bool NotifyAppPush { get; set; }

    public bool NotifySiteMessage { get; set; }

    [Precision(0)]
    public DateTime CreatedAt { get; set; }

    [Precision(0)]
    public DateTime UpdatedAt { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal? SpendingThresholdAmount { get; set; }
}