// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("MemberId", "ExpiresAt", Name = "IX_PointLots_Member_Expiry")]
public partial class PointLot
{
    [Key]
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int Points { get; set; }

    public int RemainingPoints { get; set; }

    [Required]
    [StringLength(50)]
    public string Reason { get; set; }

    [Precision(0)]
    public DateTime ExpiresAt { get; set; }

    [Precision(0)]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("PointLots")]
    public virtual Member Member { get; set; }

    [InverseProperty("Lot")]
    public virtual ICollection<PointRedemptionItem> PointRedemptionItems { get; set; } = new List<PointRedemptionItem>();
}