// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class PointRedemption
{
    [Key]
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int UsedPoints { get; set; }

    [Precision(0)]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("PointRedemptions")]
    public virtual Member Member { get; set; }

    [InverseProperty("Redemption")]
    public virtual ICollection<PointRedemptionItem> PointRedemptionItems { get; set; } = new List<PointRedemptionItem>();
}