// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class PointGrantRule
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string RuleName { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string RuleType { get; set; }

    public int Amount { get; set; }

    public int ExpiryDays { get; set; }

    [StringLength(50)]
    public string Cron { get; set; }

    [Precision(0)]
    public DateTime? StartAt { get; set; }

    [Precision(0)]
    public DateTime? EndAt { get; set; }

    [Required]
    [StringLength(30)]
    public string Target { get; set; }

    public bool IsEnabled { get; set; }

    [Precision(0)]
    public DateTime CreatedAt { get; set; }
}