// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("LotId", Name = "IX_RedemptionItems_Lot")]
[Index("RedemptionId", Name = "IX_RedemptionItems_Redemption")]
public partial class PointRedemptionItem
{
    [Key]
    public int Id { get; set; }

    public int RedemptionId { get; set; }

    public int LotId { get; set; }

    public int UsedPoints { get; set; }

    [ForeignKey("LotId")]
    [InverseProperty("PointRedemptionItems")]
    public virtual PointLot Lot { get; set; }

    [ForeignKey("RedemptionId")]
    [InverseProperty("PointRedemptionItems")]
    public virtual PointRedemption Redemption { get; set; }
}