// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[PrimaryKey("MemberId", "PostId")]
public partial class PostFavorite
{
    [Key]
    public int MemberId { get; set; }

    [Key]
    public int PostId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedTime { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("PostFavorites")]
    public virtual Member Member { get; set; }

    [ForeignKey("PostId")]
    [InverseProperty("PostFavorites")]
    public virtual Post Post { get; set; }
}