// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class PostReport
{
    [Key]
    public int Id { get; set; }

    public int PostId { get; set; }

    public int? ReporterId { get; set; }

    public int RuleId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ReportTime { get; set; }

    public int StatusId { get; set; }

    public int? ResultId { get; set; }

    [ForeignKey("PostId")]
    [InverseProperty("PostReports")]
    public virtual Post Post { get; set; }

    [ForeignKey("ReporterId")]
    [InverseProperty("PostReports")]
    public virtual Member Reporter { get; set; }

    [ForeignKey("ResultId")]
    [InverseProperty("PostReports")]
    public virtual ReportResult Result { get; set; }

    [ForeignKey("RuleId")]
    [InverseProperty("PostReports")]
    public virtual Rule Rule { get; set; }

    [ForeignKey("StatusId")]
    [InverseProperty("PostReports")]
    public virtual ReportStatus Status { get; set; }
}