// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class PostHistory
{
    [Key]
    public int Id { get; set; }

    public int? PostId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EditTime { get; set; }

    [Required]
    public string Snapshot { get; set; }

    [ForeignKey("PostId")]
    [InverseProperty("PostHistories")]
    public virtual Post Post { get; set; }
}