// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Table("PostStatus")]
[Index("Name", Name = "UQ__PostStat__737584F658A8B956", IsUnique = true)]
public partial class PostStatus
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [InverseProperty("Status")]
    public virtual ICollection<Announcement> Announcements { get; set; } = new List<Announcement>();

    [InverseProperty("Status")]
    public virtual ICollection<Event> Events { get; set; } = new List<Event>();

    [InverseProperty("Status")]
    public virtual ICollection<News> News { get; set; } = new List<News>();

    [InverseProperty("Status")]
    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}