// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class Post
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Title { get; set; }

    [Required]
    public string PostContent { get; set; }

    public int TypeId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PostTime { get; set; }

    public int NumOfHits { get; set; }

    public int NumOfGoods { get; set; }

    public int MemberId { get; set; }

    public bool IsDeleted { get; set; }

    public int StatusId { get; set; }

    [Column("ImageURL")]
    [StringLength(250)]
    public string ImageUrl { get; set; }

    [StringLength(400)]
    public string Summary { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastEditTime { get; set; }

    [InverseProperty("Post")]
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    [ForeignKey("MemberId")]
    [InverseProperty("Posts")]
    public virtual Member Member { get; set; }

    [InverseProperty("Post")]
    public virtual ICollection<PostFavorite> PostFavorites { get; set; } = new List<PostFavorite>();

    [InverseProperty("Post")]
    public virtual ICollection<PostGood> PostGoods { get; set; } = new List<PostGood>();

    [InverseProperty("Post")]
    public virtual ICollection<PostHistory> PostHistories { get; set; } = new List<PostHistory>();

    [InverseProperty("Post")]
    public virtual ICollection<PostReport> PostReports { get; set; } = new List<PostReport>();

    [ForeignKey("StatusId")]
    [InverseProperty("Posts")]
    public virtual PostStatus Status { get; set; }

    [ForeignKey("TypeId")]
    [InverseProperty("Posts")]
    public virtual PostType Type { get; set; }

    [ForeignKey("PostId")]
    [InverseProperty("Posts")]
    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
}