// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[PrimaryKey("ProductId", "PaymentId")]
[Table("ProductPayment")]
public partial class ProductPayment
{
    [Key]
    public int ProductId { get; set; }

    [Key]
    public int PaymentId { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("ProductPaymentCreatedByNavigations")]
    public virtual User CreatedByNavigation { get; set; }

    [ForeignKey("DeletedBy")]
    [InverseProperty("ProductPaymentDeletedByNavigations")]
    public virtual User DeletedByNavigation { get; set; }

    [ForeignKey("PaymentId")]
    [InverseProperty("ProductPayments")]
    public virtual PaymentMethod Payment { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductPayments")]
    public virtual Product Product { get; set; }

    [ForeignKey("UpdatedBy")]
    [InverseProperty("ProductPaymentUpdatedByNavigations")]
    public virtual User UpdatedByNavigation { get; set; }
}