// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class ProductReview
{
    [Key]
    public int Id { get; set; }

    public int ProductId { get; set; }

    public int MemberId { get; set; }

    public int Rating { get; set; }

    [StringLength(512)]
    public string Comment { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    [ForeignKey("DeletedBy")]
    [InverseProperty("ProductReviewDeletedByNavigations")]
    public virtual User DeletedByNavigation { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("ProductReviews")]
    public virtual Member Member { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductReviews")]
    public virtual Product Product { get; set; }

    [ForeignKey("UpdatedBy")]
    [InverseProperty("ProductReviewUpdatedByNavigations")]
    public virtual User UpdatedByNavigation { get; set; }
}