// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[PrimaryKey("ProductId", "DeliveryId")]
[Table("ProductDelivery")]
public partial class ProductDelivery
{
    [Key]
    public int ProductId { get; set; }

    [Key]
    public int DeliveryId { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("ProductDeliveryCreatedByNavigations")]
    public virtual User CreatedByNavigation { get; set; }

    [ForeignKey("DeletedBy")]
    [InverseProperty("ProductDeliveryDeletedByNavigations")]
    public virtual User DeletedByNavigation { get; set; }

    [ForeignKey("DeliveryId")]
    [InverseProperty("ProductDeliveries")]
    public virtual DeliveryMethod Delivery { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductDeliveries")]
    public virtual Product Product { get; set; }

    [ForeignKey("UpdatedBy")]
    [InverseProperty("ProductDeliveryUpdatedByNavigations")]
    public virtual User UpdatedByNavigation { get; set; }
}