// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Table("ProductStatus")]
[Index("StatusName", Name = "UQ__ProductS__05E7698A66B25D37", IsUnique = true)]
public partial class ProductStatus
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string StatusName { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    [InverseProperty("Status")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}