// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class Punishment
{
    [Key]
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int? TypeId { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndTime { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("Punishments")]
    public virtual Member Member { get; set; }

    [ForeignKey("TypeId")]
    [InverseProperty("Punishments")]
    public virtual PunishmentType Type { get; set; }
}