// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("Name", Name = "UQ__ReportRe__737584F675A61EEF", IsUnique = true)]
public partial class ReportResult
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [InverseProperty("Result")]
    public virtual ICollection<CommentReport> CommentReports { get; set; } = new List<CommentReport>();

    [InverseProperty("Result")]
    public virtual ICollection<PostReport> PostReports { get; set; } = new List<PostReport>();
}