// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Table("ReportStatus")]
[Index("Name", Name = "UQ__ReportSt__737584F6C411ADD1", IsUnique = true)]
public partial class ReportStatus
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [InverseProperty("Status")]
    public virtual ICollection<CommentReport> CommentReports { get; set; } = new List<CommentReport>();

    [InverseProperty("Status")]
    public virtual ICollection<PostReport> PostReports { get; set; } = new List<PostReport>();
}