// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class SearchLog
{
    [Key]
    public int Id { get; set; }

    public int? MemberId { get; set; }

    [Required]
    [StringLength(50)]
    public string Text { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Time { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("SearchLogs")]
    public virtual Member Member { get; set; }
}