// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Table("Server", Schema = "HangFire")]
[Index("LastHeartbeat", Name = "IX_HangFire_Server_LastHeartbeat")]
public partial class Server
{
    [Key]
    [StringLength(200)]
    public string Id { get; set; }

    public string Data { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastHeartbeat { get; set; }
}