// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

public partial class UserLoginLog
{
    [Key]
    public int Id { get; set; }

    public int UserId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LoginAt { get; set; }

    [Column("IPAddress")]
    [StringLength(50)]
    public string Ipaddress { get; set; }

    [StringLength(255)]
    public string UserAgent { get; set; }

    public bool? IsSuccessful { get; set; }

    [StringLength(100)]
    public string FailReason { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserLoginLogs")]
    public virtual User User { get; set; }
}