// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FUEN42Team3.Backend.Models.EfModels;

[Index("Account", Name = "UQ__Users__B0C3AC46C20D01FD", IsUnique = true)]
public partial class User
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string UserName { get; set; }

    public int RoleId { get; set; }

    [Required]
    [StringLength(50)]
    public string Account { get; set; }

    [Required]
    [StringLength(200)]
    public string Password { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [InverseProperty("LastEditByNavigation")]
    public virtual ICollection<Announcement> AnnouncementLastEditByNavigations { get; set; } = new List<Announcement>();

    [InverseProperty("Supervisor")]
    public virtual ICollection<Announcement> AnnouncementSupervisors { get; set; } = new List<Announcement>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<Brand> BrandCreatedByNavigations { get; set; } = new List<Brand>();

    [InverseProperty("DeletedByNavigation")]
    public virtual ICollection<Brand> BrandDeletedByNavigations { get; set; } = new List<Brand>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<Brand> BrandUpdatedByNavigations { get; set; } = new List<Brand>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<Category> CategoryCreatedByNavigations { get; set; } = new List<Category>();

    [InverseProperty("DeletedByNavigation")]
    public virtual ICollection<Category> CategoryDeletedByNavigations { get; set; } = new List<Category>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<Category> CategoryUpdatedByNavigations { get; set; } = new List<Category>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<CompanyEvent> CompanyEventCreatedByNavigations { get; set; } = new List<CompanyEvent>();

    [InverseProperty("DeletedByNavigation")]
    public virtual ICollection<CompanyEvent> CompanyEventDeletedByNavigations { get; set; } = new List<CompanyEvent>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<CompanyEvent> CompanyEventUpdatedByNavigations { get; set; } = new List<CompanyEvent>();

    [InverseProperty("DeletedByNavigation")]
    public virtual ICollection<CustomOrder> CustomOrderDeletedByNavigations { get; set; } = new List<CustomOrder>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<CustomOrderDesign> CustomOrderDesigns { get; set; } = new List<CustomOrderDesign>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<CustomOrder> CustomOrderUpdatedByNavigations { get; set; } = new List<CustomOrder>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<DeliveryMethod> DeliveryMethodCreatedByNavigations { get; set; } = new List<DeliveryMethod>();

    [InverseProperty("DeletedByNavigation")]
    public virtual ICollection<DeliveryMethod> DeliveryMethodDeletedByNavigations { get; set; } = new List<DeliveryMethod>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<DeliveryMethod> DeliveryMethodUpdatedByNavigations { get; set; } = new List<DeliveryMethod>();

    [InverseProperty("DeletedByNavigation")]
    public virtual ICollection<EcpayPayment> EcpayPaymentDeletedByNavigations { get; set; } = new List<EcpayPayment>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<EcpayPayment> EcpayPaymentUpdatedByNavigations { get; set; } = new List<EcpayPayment>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<Gift> GiftCreatedByNavigations { get; set; } = new List<Gift>();

    [InverseProperty("DeletedByNavigation")]
    public virtual ICollection<Gift> GiftDeletedByNavigations { get; set; } = new List<Gift>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<GiftRule> GiftRuleCreatedByNavigations { get; set; } = new List<GiftRule>();

    [InverseProperty("DeletedByNavigation")]
    public virtual ICollection<GiftRule> GiftRuleDeletedByNavigations { get; set; } = new List<GiftRule>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<GiftRuleItem> GiftRuleItemCreatedByNavigations { get; set; } = new List<GiftRuleItem>();

    [InverseProperty("DeletedByNavigation")]
    public virtual ICollection<GiftRuleItem> GiftRuleItemDeletedByNavigations { get; set; } = new List<GiftRuleItem>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<GiftRuleItem> GiftRuleItemUpdatedByNavigations { get; set; } = new List<GiftRuleItem>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<GiftRule> GiftRuleUpdatedByNavigations { get; set; } = new List<GiftRule>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<Gift> GiftUpdatedByNavigations { get; set; } = new List<Gift>();

    [InverseProperty("DeletedByNavigation")]
    public virtual ICollection<LinepayPayment> LinepayPaymentDeletedByNavigations { get; set; } = new List<LinepayPayment>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<LinepayPayment> LinepayPaymentUpdatedByNavigations { get; set; } = new List<LinepayPayment>();

    [InverseProperty("Creator")]
    public virtual ICollection<MassNotification> MassNotifications { get; set; } = new List<MassNotification>();

    [InverseProperty("User")]
    public virtual ICollection<News> News { get; set; } = new List<News>();

    [InverseProperty("DeletedByNavigation")]
    public virtual ICollection<Order> OrderDeletedByNavigations { get; set; } = new List<Order>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<OrderGift> OrderGiftCreatedByNavigations { get; set; } = new List<OrderGift>();

    [InverseProperty("DeletedByNavigation")]
    public virtual ICollection<OrderGift> OrderGiftDeletedByNavigations { get; set; } = new List<OrderGift>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<OrderGift> OrderGiftUpdatedByNavigations { get; set; } = new List<OrderGift>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<Order> OrderUpdatedByNavigations { get; set; } = new List<Order>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<PaymentMethod> PaymentMethodCreatedByNavigations { get; set; } = new List<PaymentMethod>();

    [InverseProperty("DeletedByNavigation")]
    public virtual ICollection<PaymentMethod> PaymentMethodDeletedByNavigations { get; set; } = new List<PaymentMethod>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<PaymentMethod> PaymentMethodUpdatedByNavigations { get; set; } = new List<PaymentMethod>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<Product> ProductCreatedByNavigations { get; set; } = new List<Product>();

    [InverseProperty("DeletedByNavigation")]
    public virtual ICollection<Product> ProductDeletedByNavigations { get; set; } = new List<Product>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<ProductDelivery> ProductDeliveryCreatedByNavigations { get; set; } = new List<ProductDelivery>();

    [InverseProperty("DeletedByNavigation")]
    public virtual ICollection<ProductDelivery> ProductDeliveryDeletedByNavigations { get; set; } = new List<ProductDelivery>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<ProductDelivery> ProductDeliveryUpdatedByNavigations { get; set; } = new List<ProductDelivery>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<ProductImage> ProductImageCreatedByNavigations { get; set; } = new List<ProductImage>();

    [InverseProperty("DeletedByNavigation")]
    public virtual ICollection<ProductImage> ProductImageDeletedByNavigations { get; set; } = new List<ProductImage>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<ProductImage> ProductImageUpdatedByNavigations { get; set; } = new List<ProductImage>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<ProductPayment> ProductPaymentCreatedByNavigations { get; set; } = new List<ProductPayment>();

    [InverseProperty("DeletedByNavigation")]
    public virtual ICollection<ProductPayment> ProductPaymentDeletedByNavigations { get; set; } = new List<ProductPayment>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<ProductPayment> ProductPaymentUpdatedByNavigations { get; set; } = new List<ProductPayment>();

    [InverseProperty("DeletedByNavigation")]
    public virtual ICollection<ProductReview> ProductReviewDeletedByNavigations { get; set; } = new List<ProductReview>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<ProductReview> ProductReviewUpdatedByNavigations { get; set; } = new List<ProductReview>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<Product> ProductUpdatedByNavigations { get; set; } = new List<Product>();

    [ForeignKey("RoleId")]
    [InverseProperty("Users")]
    public virtual UserRole Role { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<UserLoginLog> UserLoginLogs { get; set; } = new List<UserLoginLog>();
}